name: build + upload

on:
  push:
    branches:
      - master
      - release
      - 'feature/**'
      - 'hotfix/**'
      - 'aws-lambda'
      - 'feature1'
    tags:
      - r*
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Output of required variable
        run: echo "Output =========== ${{ github.event.pull_request.merged }} haha"

      - name: Build with Gradle
        if: github.event.pull_request.merged == 'false'
        run: gradle build

      - name: Build with Gradle(skip tests on merge)
        if: github.event.pull_request.merged == 'true'
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
